FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /App

# Copy everything
COPY . ./
# Restore as distinct layers
RUN dotnet restore "B3Challenge.Task.Worker/B3Challenge.Task.Worker.csproj"
# Build and publish a release
RUN dotnet publish "B3Challenge.Task.Worker/B3Challenge.Task.Worker.csproj" -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /App
COPY --from=build-env /App/out .

#ENTRYPOINT ["dotnet", "B3Challenge.Task.Worker.exe"]

#FROM microsoft/dotnet:6.0-runtime AS base
#WORKDIR /app
 #
#FROM microsoft/dotnet:6.0-sdk AS build
#WORKDIR /src
#COPY *.sln ./
#COPY . /B3Challenge.Task.Worker/B3Challenge.Task.Worker.csproj /B3Challenge.Task.Worker/
#RUN dotnet restore
#COPY . .
#WORKDIR /src/
#RUN dotnet build -c Release -o /app
 #
#FROM build AS publish
#RUN dotnet publish -c Release -o /app
 #
#FROM base AS final
#WORKDIR /app
#COPY --from=publish /app/ .
#ENTRYPOINT ["dotnet", "B3Challenge.Task.Worker.exe"]